### ISSUE TITLE
ReferenceError: IFrameMobilePreview is not defined

### ISSUE THREAD

**Issue by ajmalafif** [Jesperpaulsen/sanity-mobile-preview#1]
Hi there, 

I believe I follow the README properly and thoroughly but couldn‘t figure out what I did wrong. I keep getting this error on my Sanity Studio:
<img width="1279" alt="afif_dev_–_Sanity" src="https://user-images.githubusercontent.com/827167/101349081-b6b69b00-38c7-11eb-9a7c-b4fb4e52363a.png">

Here‘s the branch which I attempted to install `sanity-mobile-preview` 
- https://github.com/ajmalafif/afif.dev/blob/sanity-mobile-preview/studio/src/previews/IframeMobilePreview.js
- https://github.com/ajmalafif/afif.dev/blob/dfd167782839082682e995f6e4b801d09aa3693c/studio/src/structure/deskStructure.js#L33

Appreciate any pointers so I can make it work. Thanks!

**Comment by Jesperpaulsen** [comment]
Hi @ajmalafif 😄 

Thanks for submitting the issue!

Took a quick look at your code, and at line 34 you're referencing IFrameMobilePreview with capital F, while you import it as IframeMobilePreview at line 9, without capital F. Can you try to change it, and see if that works? 🙂 

https://github.com/ajmalafif/afif.dev/blob/sanity-mobile-preview/studio/src/structure/deskStructure.js#L34

Looked at the Readme, and I see that I'm not consequent with the lower/upper case on IFrame vs Iframe. I will make sure to update the Readme 🤠

**Comment by ajmalafif** [comment]
Hi @Jesperpaulsen!

No THANK YOU SO MUCH for the swift reply and sharp eyes. That fixes it!

**Comment by Jesperpaulsen** [comment]
@ajmalafif I'm glad I could help. Let me know if you run into any other problems or have suggestions to improve the plugin!

**Comment by ajmalafif** [comment]
Definitely! 

I reckon should I create new issue or just comment here?

As a designer first, I noticed small details like the scroll bar doesn't reflect the scroll bar on mobile browsers so curious if that's more of stylistic changes or there's some settings need to be changed to reflect that.

**Comment by Jesperpaulsen** [comment]
I guess you can open a new issue, so it will be easier for others to see them as well!

When it comes to the styling of the scrollbar, I absolutely agree. At the moment the scrollbar that is shown is using the same scrollbar as the browser you're viewing it in. It will take a bit more logic to override the appearance from the plugin, as it at the moment doesn't handle the actual iFrame. So in the meantime, I guess you could try to style the appearance of the iFrame directly 🙂  The iFrame can be styled in the same way as regular HTML Elements, as shown [here](https://stackoverflow.com/questions/217776/how-to-apply-css-to-iframe). Let me know if you try it out and if it works, we can try to add your design to the plugin 😃

**Comment by ajmalafif** [comment]
Got it. I'll probably tinker around and see if there is actual progress and improvement I could contribute. Will share my findings. Thanks again for the package and help!
