### ISSUE TITLE
Depend on React 17+

### ISSUE THREAD

**Issue by runeb** [Jesperpaulsen/sanity-mobile-preview#3]
It would be good if this module could depend on react16+ and react17+

```
"react": "^16 || ^17"
```

**Comment by Jesperpaulsen** [comment]
> It would be good if this module could depend on react16+ and react17+
> 
> 
> 
> ```
> 
> "react": "^16 || ^17"
> 
> ```

Thanks for the heads up! Will fix this tomorrow @runeb

**Comment by Jesperpaulsen** [comment]
Bumped the dependencies now @runeb and published version 1.0.8 to NPM.
